// Project1.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include "LinkedList.h"
#include "FileHandler.h"


using namespace std;

void tokenize(string review, LinkedList& list) {
    string word = "";
    for (char c : review) {
        if ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')) {
            if (c >= 'A' && c <= 'Z') {
                c = c + 32; // Convert to lowercase by adding ASCII offset
            }
            word += c;
        }
        else {
            if (!word.empty()) {
                list.insertFront(word);
                word = "";
            }
        }
    }

    if (!word.empty()) {
        list.insertFront(word);
    }
}

int calculateSentimentScore(int positiveCount, int negativeCount) {
    int N = positiveCount + negativeCount;
    int rawScore = positiveCount - negativeCount;
    int minRawScore = -N;
    int maxRawScore = N;

    if (maxRawScore == minRawScore) return 3;

    float normalizedScore = float(rawScore - minRawScore) / (maxRawScore - minRawScore);
    return round(1.0f + (4.0f * normalizedScore));
}

// compare sentimental score and the rating given
void analyzeScore(int sentimentScore, int ratingGiven) {
    string result = (sentimentScore != ratingGiven) ? "does not match" : "matches";
    string consistency = (sentimentScore != ratingGiven) ? "inconsistency" : "consistency";

    cout << "User's subjective evaluation " << result << " the sentiment score provided by the analysis. "
        << "There is a " << consistency << " between the sentiment score generated by the analysis and the user's evaluation of the sentiment."
        << endl << endl;
}


//void analyzeReviews(LinkedList& reviews) {
//
//}

int main()
{
    LinkedList reviewsList, negativeList, positiveList, wordList, accumulatedWordList;
	readReviewsFromCSV("tripadvisor_hotel_reviews.csv", reviewsList);
	readWordFromText("negative-words.txt", negativeList);
	readWordFromText("positive-words.txt", positiveList);

    int totalPositiveCount = 0;
    int totalNegativeCount = 0;
    int reviewCount = 1;
    
    negativeList.quickSort();
    positiveList.quickSort();
    wordList.quickSort();

    Node* currentReviewNode = reviewsList.getHead();
    while (currentReviewNode != nullptr) {
        cout << string(50, '=') << endl;
        cout << "Review " << reviewCount << ": " << currentReviewNode->review << endl << endl;
        tokenize(currentReviewNode->review, wordList);

        WordNode* tempWord = wordList.getWordHead();
        LinkedList foundPositiveWords, foundNegativeWords;

        int positiveCount = 0;
        int negativeCount = 0;

        while (tempWord) {
            if (positiveList.binarySearch(tempWord->word)) {
                positiveCount++;
                totalPositiveCount++;
                accumulatedWordList.checkDuped(tempWord->word);
                foundPositiveWords.checkDuped(tempWord->word);
            }

            if (negativeList.binarySearch(tempWord->word)) {
                negativeCount++;
                totalNegativeCount++;
                accumulatedWordList.checkDuped(tempWord->word);
                foundNegativeWords.checkDuped(tempWord->word);
            }

            tempWord = tempWord->nextAddress;
        }

        // Display analysis result for current review
        // Positive words found
        cout << positiveCount << " postive words found in the review: " << endl;
        foundPositiveWords.displayList();

        // Negative words found
        cout << negativeCount << " negative words found in the review: " << endl;
        foundNegativeWords.displayList();

        // Calculate sentimental score based on total positive words and negative words found in review
        int sentimentScore = calculateSentimentScore(positiveCount, negativeCount);
        cout << "Sentiment Score (1-5) = " << sentimentScore << endl;
        cout << "Rating given by User =  " << currentReviewNode->rating << endl;

        // analyze rating of review
        analyzeScore(sentimentScore, stoi(currentReviewNode->rating));
        cout << string(50, '=') << endl;

        wordList = LinkedList();
        reviewCount++;
        currentReviewNode = currentReviewNode->nextAddress;
    }

    // Overall review analysis result
    accumulatedWordList.quickSortByFrequency();

    // Display overall summary
    cout << "Total Reviews Processed = " << reviewCount - 1 << endl;
    cout << "Total Count of Positive Words = " << totalPositiveCount << endl;
    cout << "Total Count of Negative Words = " << totalNegativeCount << endl;

    // Display the accumulated full word list (sorted by frequency)
    cout << "Full Word List (from all reviews, sorted by frequency):" << endl;
    accumulatedWordList.printReport();

}

